services:
  stats-server:
    build: stats-service/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - STATS-SERVER.URL=http://stats-server:9090
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver